[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.2"
array-init = "2.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
